# Конфігурація для AI-асистентів, що працюють з проектом Forex Data Analytics

# Базові налаштування
settings:
  language: "українська"  # Мова для відповідей AI
  project_name: "Forex Data Analytics"
  version: "1.0.0"
  author: "Vitalii"
  description: "Інструмент для аналізу форекс-даних з різних часових інтервалів, розрахунку метрик та інтеграції з Notion"

# Загальний опис проекту
project:
  overview: >
    Проект створений для аналізу даних валютного ринку Forex. Він обробляє сирі дані з хвилинним таймфреймом,
    створює різні часові інтервали (1m, 5m, 15m, 1h, 4h, 1d, 1w), розраховує комплексні метрики ринку
    та завантажує їх до бази даних Notion для подальшого аналізу. Програма підтримує кілька профілів
    користувачів (Whytalik, Mordan, Infobase) з індивідуальними налаштуваннями метрик для кожного.
    
  key_features:
    - Обробка та конвертація сирих даних CSV з валютного ринку
    - Створення різних часових інтервалів (1m, 5m, 15m, 1h, 4h, 1d, 1w)
    - Розрахунок метрик волатильності та діапазонів цін
    - Аналіз розподілу максимумів і мінімумів за торговими сесіями
    - Статистика виникнення подій за днями тижня
    - Аналіз ключових рівнів і точок повороту ринку
    - Інтеграція з API Notion для зберігання та візуалізації даних
    - Підтримка кількох профілів користувачів з різними наборами метрик

# Структура директорій та файлів
structure:
  directories:
    src:
      description: "Кореневий каталог з кодом проекту"
      subdirectories:
        app:
          description: "Основний код програми"
          files:
            - "main.py": "Головний файл програми, що керує всім процесом аналізу даних"
        
        config:
          description: "Файли конфігурації"
          files:
            - "settings.py": "Загальні налаштування шляхів до файлів"
            - "timeframes_config.py": "Конфігурація часових інтервалів"
            - "sessions_config.py": "Налаштування торгових сесій (Азія, Франкфурт, Лондон, тощо)"
            - "pairs_config.py": "Конфігурація валютних пар та їх властивостей"
            - "notion_settings.py": "Налаштування API Notion та профілів"
            - "metrics_config.py": "Конфігурація метрик та їх групування"
          subdirectories:
            metrics:
              description: "Детальні конфігурації метрик за категоріями"
              files:
                - "levels_metrics.py": "Конфігурація метрик для ключових рівнів"
                - "occurrence_statistics_metrics.py": "Метрики статистики виникнення подій"
                - "range_metrics.py": "Метрики діапазонів цін"
                - "session_timing_distribution_metrics.py": "Метрики розподілу часу сесій"
                - "sessions_interactions.py": "Метрики взаємодії між сесіями"
        
        services:
          description: "Сервіси для обробки даних та інтеграції"
          subdirectories:
            csv:
              description: "Сервіси для роботи з CSV-файлами"
              files:
                - "__init__.py": "Ініціалізаційний файл пакету"
                - "collector.py": "Збір CSV-файлів з директорій"
                - "merger.py": "Об'єднання CSV-файлів"
                - "formatter.py": "Форматування даних у потрібний формат"
                - "timeframes_creator.py": "Створення різних часових інтервалів"
            
            notion:
              description: "Сервіси для інтеграції з Notion API"
              files:
                - "__init__.py": "Ініціалізаційний файл пакету"
                - "client.py": "Основний клієнт для API Notion"
                - "http_handler.py": "Обробник HTTP-запитів з повторними спробами"
                - "properties_manager.py": "Керування властивостями бази даних Notion"
                - "metrics_uploader.py": "Завантаження метрик до Notion"
            
            metrics:
              description: "Сервіси для розрахунку метрик"
              files:
                - "__init__.py": "Ініціалізаційний файл пакету"
                - "base_metric.py": "Базовий клас для всіх метрик"
                - "metrics_manager.py": "Керування розрахунком метрик"
              subdirectories:
                calculators:
                  description: "Калькулятори для різних типів метрик"
                  files:
                    - "volatility_metrics.py": "Розрахунок метрик волатильності"
                    - "session_distribution_metrics.py": "Розрахунок метрик розподілу сесій"
                    - "intraday_metrics.py": "Розрахунок внутрішньоденних метрик"
                    - "occurrence_metrics.py": "Розрахунок метрик виникнення подій"
                    - "levels_metrics.py": "Розрахунок метрик рівнів"
                    - "directional_metrics.py": "Розрахунок направлених метрик"
            
            performance:
              description: "Сервіси для моніторингу продуктивності"
              files:
                - "__init__.py": "Ініціалізаційний файл пакету"
                - "monitor.py": "Моніторинг системних ресурсів"
                - "decorators.py": "Декоратори для вимірювання часу виконання"
                - "config_manager.py": "Керування конфігурацією для оптимальної продуктивності"
                - "cache.py": "Кешування даних для покращення продуктивності"
          
          files:
            - "__init__.py": "Ініціалізаційний файл пакету"
            - "metrics_service.py": "Основний сервіс для розрахунку метрик"
            - "metrics_profile_service.py": "Сервіс для керування профільними метриками"
        
    data:
      description: "Директорія для зберігання даних"
      subdirectories:
        raw:
          description: "Сирі дані з валютного ринку у форматі CSV"
        processed:
          description: "Оброблені об'єднані файли даних"
        formatted:
          description: "Відформатовані дані у стандартному форматі"
        timeframes:
          description: "Дані різних часових інтервалів (1m, 5m, 15m, 1h, 4h, 1d, 1w)"

# Детальний опис ключових компонентів
components:
  csv_processing:
    description: "Обробка CSV-файлів форекс-даних"
    responsibility: "Збір, об'єднання, форматування та створення різних часових інтервалів"
    key_files:
      - "services/csv/timeframes_creator.py": "Створення даних різних часових інтервалів з сирих даних"
    details: >
      Модуль обробляє сирі дані CSV, об'єднує їх, форматує та створює набори даних для різних
      часових інтервалів. Особливу увагу приділено правильному формуванню тижневих та денних свічок
      відповідно до стандартів форекс-ринку (день починається о 21:00 UTC).

  metrics_calculation:
    description: "Розрахунок аналітичних метрик"
    responsibility: "Розрахунок різноманітних метрик на основі даних різних часових інтервалів"
    key_files:
      - "services/metrics/metrics_manager.py": "Керування всіма калькуляторами метрик"
      - "services/metrics/calculators/*.py": "Спеціалізовані калькулятори для різних типів метрик"
    details: >
      Система розраховує понад 50 різних метрик, включаючи волатильність, розподіл сесій,
      статистику виникнення подій, ключові рівні та інші показники. Розрахунки проводяться
      на основі даних різних часових інтервалів та включають спеціалізовані алгоритми
      для виявлення ринкових паттернів.

  notion_integration:
    description: "Інтеграція з Notion API"
    responsibility: "Завантаження розрахованих метрик до баз даних Notion"
    key_files:
      - "services/notion/client.py": "Основний клієнт для API Notion"
      - "services/notion/properties_manager.py": "Керування властивостями бази даних"
      - "services/notion/metrics_uploader.py": "Завантаження метрик"
    details: >
      Система інтегрується з API Notion для зберігання розрахованих метрик. Підтримує
      кілька профілів з окремими базами даних, автоматично створює необхідні властивості
      та завантажує дані партіями для оптимальної продуктивності.

  performance_optimization:
    description: "Оптимізація продуктивності"
    responsibility: "Моніторинг та оптимізація використання ресурсів"
    key_files:
      - "services/performance/monitor.py": "Моніторинг системних ресурсів"
      - "services/performance/cache.py": "Кешування даних"
    details: >
      Система включає інструменти для моніторингу використання ресурсів, кешування даних
      та оптимізації конкурентного виконання операцій. Це забезпечує ефективну роботу
      навіть з великими обсягами даних.

# Специфічні інструкції для AI моделей
ai_instructions:
  context: >
    Цей проект є інструментом для аналізу даних валютного ринку Forex. Він опрацьовує сирі дані,
    створює різні часові інтервали, розраховує метрики та інтегрується з Notion.
  
  response_style:
    - Відповідати українською мовою
    - Використовувати технічну термінологію, пов'язану з аналізом фінансових ринків
    - Надавати конкретні приклади коду при необхідності
    - Пояснювати складні концепції простими словами

  common_questions:
    data_format: >
      Сирі дані представлені в форматі CSV з полями: дата/час, відкриття, максимум, мінімум, закриття.
      Приклад: 20240101 170000;1.104270;1.104290;1.104250;1.104290;0
    
    timeframes: >
      Проект підтримує наступні часові інтервали: 1 хвилина (1m), 5 хвилин (5m), 15 хвилин (15m),
      1 година (1h), 4 години (4h), 1 день (1d), 1 тиждень (1w).
    
    metrics: >
      Основні категорії метрик: волатильність та діапазони цін, розподіл максимумів і мінімумів
      за торговими сесіями, внутрішньоденна статистика, статистика виникнення подій за днями тижня,
      аналіз ключових рівнів.
    
    notion_integration: >
      Інтеграція з Notion використовує офіційний API для створення властивостей бази даних
      та завантаження розрахованих метрик. Підтримуються три профілі: Whytalik, Mordan, Infobase.

# Вказівки щодо обслуговування файлу конфігурації
maintenance:
  description: >
    Цей файл конфігурації є критично важливим для правильної роботи AI-асистентів з проектом.
    Він містить детальний опис структури проекту, його компонентів та функціональності.
  
  update_requirements:
    - "Оновлювати цей файл при кожному суттєвому виправленні або зміні в коді проекту"
    - "Додавати нові компоненти, сервіси або функціональність, як тільки вони впроваджені"
    - "Оновлювати опис структури директорій при створенні нових файлів або зміні їх призначення"
    - "Модифікувати опис конфігурацій при зміні їх формату або призначення"
    - "Актуалізувати розділ 'common_questions' відповідно до нових типових запитань"

  importance: >
    Підтримання актуальності цього файлу конфігурації забезпечує точне розуміння AI-асистентами
    структури проекту та його функціональності, що дозволяє надавати більш релевантні та 
    корисні відповіді на запити щодо проекту. Кожне суттєве виправлення в коді повинно 
    супроводжуватися відповідним оновленням цього файлу для забезпечення синхронізації 
    документації з фактичним станом проекту.

  known_issues:
    description: "Відомі проблеми та плановані виправлення"
    issues:
      - description: "Помилка при формуванні 1D та 1W часових інтервалів"
        details: >
          При створенні денних та тижневих часових інтервалів виникає помилка пов'язана з 
          відсутністю DatetimeIndex: 'Only valid with DatetimeIndex, TimedeltaIndex or 
          PeriodIndex, but got an instance of Index'
        status: "Виправлено"
        fix: "Додано перетворення стовпця дати на DatetimeIndex перед операцією resample"
        files_affected:
          - "services/csv/timeframes_creator.py"
