NOTION_METRICS = {
    "Volatility & Range Metrics": [
        "Average Daily Range (pips)",
        "Average Weekly Range (pips)",
        "Average London Range",
        "Average NY Range",
        "Average Frankfurt Range",
        "Average Asia Range",
        "Average Lunch Range",
        "Average Daily Body Size (pips)",
        "Average Weekly Body Size (pips)",
    ],
    "High/Low Timing Distribution (per Session)": [
        "Daily High in Asia %",
        "Daily High in Frankfurt %",
        "Daily High in London %",
        "Daily High in NY %",
        "Daily High in Lunch %",
        "Daily High in Out of Session %",
        "Daily Low in Asia %",
        "Daily Low in Frankfurt %",
        "Daily Low in London %",
        "Daily Low in NY %",
        "Daily Low in Lunch %",
        "Daily Low in Out of Session %",
    ],
    "Intraday Interval High/Low Percentages": [
        "NY-London High %",
        "NY-London Low %",
        "NY-Lunch High %",
        "NY-Lunch Low %",
        "NY-Frankfurt High %",
        "NY-Frankfurt Low %",
        "Lunch-Asia High %",
        "Lunch-Asia Low %",
        "Lunch-London High %",
        "Lunch-London Low %",
        "Lunch-Frankfurt High %",
        "Lunch-Frankfurt Low %",
        "London-Frankfurt High %",
        "London-Frankfurt Low %",
        "Frankfurt-Asia High %",
        "Frankfurt-Asia Low %",
        "London-Asia High %",
        "London-Asia Low %",
        "NY-Asia High %",
        "NY-Asia Low %",
    ],
    "Bullish / Bearish Specific Metrics": [
        "Bullish NY-London High %",
        "Bullish NY-Lunch High %",
        "Bullish NY-Frankfurt High %",
        "Bullish NY-Asia High %",
        "Bullish Frankfurt-Asia High %",
        "Bullish London-Asia High %",
        "Bullish Lunch-Asia High %",
        "Bullish Lunch-Frankfurt High %",
        "Bullish Lunch-London High %",
        "Bullish London-Frankfurt High %",
        "Bearish Day High & Low Statistics",
    ],
    "Daily/Weekly Occurrence Statistics": [
        "High in Monday",
        "High in Tuesday",
        "High in Wednesday",
        "High in Thursday",
        "High in Friday",
        "Low in Monday",
        "Low in Tuesday",
        "Low in Wednesday",
        "Low in Thursday",
        "Low in Friday",
        "PDH Probability",
        "PDL Probability",
        "PDH/PDL Probability",
    ],
    "Aggregated / Thematic Metrics": [
        "Date Range",
    ],
}
